name: Build LaTeX Resume

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            src/resume/versions/resume-fr.tex
            src/resume/versions/resume-en.tex

      - name: PDFs dir
        run: |
          mkdir -p pdfs
          mv resume-fr.pdf pdfs/resume-fr.pdf
          mv resume-en.pdf pdfs/resume-en.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: pdfs
